### ISSUE TITLE
Will there be any support of HDMI?

### ISSUE THREAD

**Issue by St7530** [FluffyCuteOwO/Redmibook14-EE-hackintosh#10]
I tried connecting my monitor by HDMI on Ventura, and found it just didn't work.
Is there a way for me to connect a monitor through HDMI? Thank you so much.

**Comment by michitta** [comment]
> I tried connecting my monitor by HDMI on Ventura, and found it just didn't work. Is there a way for me to connect a monitor through HDMI? Thank you so much.

Hello. You can try the new EFI.
