### ISSUE TITLE
Does it support HDMI output?

### ISSUE THREAD

**Issue by vercen** [FluffyCuteOwO/Redmibook14-EE-hackintosh#11]
I want to use a monitor. Does it support HDMI?

**Comment by michitta** [comment]
> I want to use a monitor. Does it support HDMI?

Hello. Yes, you can use the monitor via HDMI. But I don't remember if the latest EFI release has an HDMI fix. It didn't work in some versions.

**Comment by michitta** [comment]
> I want to use a monitor. Does it support HDMI?

Hello. You can try the new EFI.
