### ISSUE TITLE
Does it support NVMe SSD?

### ISSUE THREAD

**Issue by St7530** [FluffyCuteOwO/Redmibook14-EE-hackintosh#12]
I plan to change to an NVMe SSD to improve the speed. Does the model of the SSD matters? Or which NVMe SSD do you recommend for RedmiBook 14 EE (i5-10210U)? Thanks a lot!!

**Comment by michitta** [comment]
> I plan to change to an NVMe SSD to improve the speed. Does the model of the SSD matters? Or which NVMe SSD do you recommend for RedmiBook 14 EE (i5-10210U)? Thanks a lot!!

Some SSDs may not be supported by macOS. Read the topic forums before purchasing.
