### ISSUE TITLE
The microphone of 3.5mm headphones doesn't work

### ISSUE THREAD

**Issue by St7530** [FluffyCuteOwO/Redmibook14-EE-hackintosh#3]
Hi, I find that when I plug in the 3.5mm headphones, only the output normally works. The input doesn't work at all. Could you please offer me the solution to the problem? Thank you so much. :-)

macOS Big Sur 11.6.3, using the latest EFI from release

**Comment by michitta** [comment]
> Hi, I find that when I plug in the 3.5mm headphones, only the output normally works

Hello! You need to use it https://github.com/hackintosh-stuff/ComboJack

**Comment by St7530** [comment]
> > Hi, I find that when I plug in the 3.5mm headphones, only the output normally works
> 
> Hello! You need to use it https://github.com/hackintosh-stuff/ComboJack

Maybe I still can't work it out🤣

**Comment by michitta** [comment]
> > > Hi, I find that when I plug in the 3.5mm headphones, only the output normally works
> > 
> > 
> > Hello! You need to use it https://github.com/hackintosh-stuff/ComboJack
> 
> Maybe I still can't work it out🤣

Try this:

- Run the following command in Terminal:

```shell
sh -c "$(curl -fsSL https://raw.githubusercontent.com/daliansky/XiaoMi-Pro-Hackintosh/main/ALCPlugFix/one-key-alcplugfix.sh)"
```

- When it's done, restart your computer. The installation now completes.

ATTENTION: You may have to replug the headphone after every boot to let headphone work.

You can check additional info here https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/main/ALCPlugFix

**Comment by St7530** [comment]
> > Hi, I find that when I plug in the 3.5mm headphones, only the output normally works
> 
> Hello! You need to use it https://github.com/hackintosh-stuff/ComboJack

When I do this on Big Sur as well as choosing the Headset option, it works fine!! Thank you so much!
