### ISSUE TITLE
контакты

### ISSUE THREAD

**Issue by nsbrokeboy** [FluffyCuteOwO/Redmibook14-EE-hackintosh#4]
Привет, не могу написать тебе в дискорде - ссылка не работает. Не мог бы ты оставить какой нибудь свой конакт для связи, хотел попросить о помощи с установкой.

**Comment by michitta** [comment]
> Привет, не могу написать тебе в дискорде - ссылка не работает. Не мог бы ты оставить какой нибудь свой конакт для связи, хотел попросить о помощи с установкой.

Здравствуйте! Я не предоставляю помощь в установке через discord и прочие, но могу Вам в кратце рассказать, что нужно делать.

В настощий момент самая стабильная система - это BigSur. На monterey есть проблемы с качеством звука в наушниках (bluetooth). На BigSur есть проблема со сном, которую я уже пофиксил, но пока ещё не выложил EFI в открытый доступ.

Гайд тут:
https://4pda.to/forum/index.php?showtopic=958686&st=1740#entry106362511

EFI в релизах

Торрент 
https://rutracker.org/forum/viewtopic.php?t=5928524
скачайте с VPN

Удачи!

**Comment by nsbrokeboy** [comment]
Спасибо за ответ! Просто дело еще в том, что мой redmibook на i5-8265u процессоре, и я не особо понимаю, что мне нужно поменять (и нужно ли вообще):)
