### ISSUE TITLE
Installation cannot continue after the installer reboot

### ISSUE THREAD

**Issue by GceCold** [FluffyCuteOwO/Redmibook14-EE-hackintosh#6]
The installation cannot continue after the installer reboot.

Test Version: 11.6.2 12.0.1

The log at the second boot

![2](https://user-images.githubusercontent.com/16684508/198870240-a8e935b7-2a2d-4ee7-89c0-5b2c8e86dbd2.png)

**Comment by St7530** [comment]
It seems that I meet the same problem when installing macOS Ventura. Have you solved that?

**Comment by michitta** [comment]
Try using the new EFI

**Comment by GceCold** [comment]
> Try using the new EFI

2.1.0 ? This is the version I was using before.

**Comment by michitta** [comment]
> > Try using the new EFI
> 
> 2.1.0 ? This is the version I was using before.

What CPU you using? intel 10th or intel 8th?

**Comment by St7530** [comment]
> > > Try using the new EFI
> > 
> > 
> > 2.1.0 ? This is the version I was using before.
> 
> What CPU you using? intel 10th or intel 8th?

What if I'm using the 10th CPU? Intel i5-10210U, thx

**Comment by michitta** [comment]
> > > > Try using the new EFI
> > > 
> > > 
> > > 2.1.0 ? This is the version I was using before.
> > 
> > 
> > What CPU you using? intel 10th or intel 8th?
> 
> What if I'm using the 10th CPU? Intel i5-10210U, thx

Nothing wrong. It's just that I haven't tested the work on the eighth generation, that's why I'm asking.

**Comment by St7530** [comment]
OK. By the way, when I reboot on Monterey, the keyboard doesn't work on OpenCore picker. The F2 and F12 key cannot work, either. So I have to use a mouse instead. Is that a common failing?

**Comment by michitta** [comment]
> OK. By the way, when I reboot on Monterey, the keyboard doesn't work on OpenCore picker. The F2 and F12 key cannot work, either. So I have to use a mouse instead. Is that a common failing? Message ID: ***@***.***&gt;

As far as I know, not everyone has this problem. Unfortunately, I have not yet been able to understand why it occurs. If you find a solution on the forums, you can offer it.

**Comment by michitta** [comment]
> > Try using the new EFI
> 
> 2.1.0 ? This is the version I was using before.

Most likely you have a problem with your installer. Try to use some other one.

**Comment by michitta** [comment]
I got confused in the comments)

**Comment by michitta** [comment]
> OK. By the way, when I reboot on Monterey, the keyboard doesn't work on OpenCore picker. The F2 and F12 key cannot work, either. So I have to use a mouse instead. Is that a common failing? Message ID: ***@***.***&gt;

You can roll back to big sur. Everything works fine on this OC.

**Comment by St7530** [comment]
> > OK. By the way, when I reboot on Monterey, the keyboard doesn't work on OpenCore picker. The F2 and F12 key cannot work, either. So I have to use a mouse instead. Is that a common failing? Message ID: _**@**_.***>
> 
> As far as I know, not everyone has this problem. Unfortunately, I have not yet been able to understand why it occurs. If you find a solution on the forums, you can offer it.

Accroding to this blog, it is the new shutdown method on Monterey that results in the annoying problem.
https://hpglw.com/3a0d9306.html

And this one gives a suggestion —— using the new `VoodooPS2Controller.kext`, add `kbd_fixdisable=1` to `boot-args`. I don't know whether it will work or not.
https://zhuanlan.zhihu.com/p/581274059

**Comment by St7530** [comment]
> > OK. By the way, when I reboot on Monterey, the keyboard doesn't work on OpenCore picker. The F2 and F12 key cannot work, either. So I have to use a mouse instead. Is that a common failing? Message ID: _**@**_.***>
> 
> You can roll back to big sur. Everything works fine on this OC.

Exactly. Thank you for your work. 👍

**Comment by michitta** [comment]
> > > OK. By the way, when I reboot on Monterey, the keyboard doesn't work on OpenCore picker. The F2 and F12 key cannot work, either. So I have to use a mouse instead. Is that a common failing? Message ID: _**@**_.***>
> > 
> > 
> > As far as I know, not everyone has this problem. Unfortunately, I have not yet been able to understand why it occurs. If you find a solution on the forums, you can offer it.
> 
> Accroding to this blog, it is the new shutdown method on Monterey that results in the annoying problem. https://hpglw.com/3a0d9306.html
> 
> And this one gives a suggestion —— using the new `VoodooPS2Controller.kext`, add `kbd_fixdisable=1` to `boot-args`. I don't know whether it will work or not. https://zhuanlan.zhihu.com/p/581274059

Unfortunately, I won't be able to check this in the near future, but thank you for a possible solution to this problem.

**Comment by michitta** [comment]
> > > OK. By the way, when I reboot on Monterey, the keyboard doesn't work on OpenCore picker. The F2 and F12 key cannot work, either. So I have to use a mouse instead. Is that a common failing? Message ID: _**@**_.***>
> > 
> > 
> > You can roll back to big sur. Everything works fine on this OC.
> 
> Exactly. Thank you for your work. 👍

😉

**Comment by GceCold** [comment]
> > > Try using the new EFI
> > 
> > 
> > 2.1.0 ? This is the version I was using before.
> 
> What CPU you using? intel 10th or intel 8th?

My CPU is also i5-10210u, but I keep having the problems. I can't complete the installation.

**Comment by GceCold** [comment]
> It seems that I meet the same problem when installing macOS Ventura. Have you solved that?

Have you solved the installation problem?

**Comment by St7530** [comment]
> > It seems that I meet the same problem when installing macOS Ventura. Have you solved that?
> 
> Have you solved the installation problem?

Not yet. Due to so many problems, I rolled back to Big Sur. I think all is fine on Big Sur.

**Comment by GceCold** [comment]
> > > It seems that I meet the same problem when installing macOS Ventura. Have you solved that?
> > 
> > 
> > Have you solved the installation problem?
> 
> Not yet. Due to so many problems, I rolled back to Big Sur. I think all is fine on Big Sur.

I also tested Big Sur, but the same error occured. There are some answers that say it's a BIOS problem.

**Comment by St7530** [comment]
> > > > It seems that I meet the same problem when installing macOS Ventura. Have you solved that?
> > > 
> > > 
> > > Have you solved the installation problem?
> > 
> > 
> > Not yet. Due to so many problems, I rolled back to Big Sur. I think all is fine on Big Sur.
> 
> I also tested Big Sur, but the same error occured. There are some answers that say it's a BIOS problem.

I know what you mean. Maybe there is still some problems. You can complete the Big Sur installation by using this CLOVER EFI.
New link: https://st7530.lanzout.com/itj3U0hckuuf

**Comment by GceCold** [comment]
> Thank you for your work.

Thank you for your work. :relaxed:

**Comment by St7530** [comment]
@FluffyCuteOwO Using the latest EFI (2.2.0, pre-released), I can now complete the Ventura installation normally. The keyboard problem has also been solved. THANKS!

**Comment by michitta** [comment]
> @FluffyCuteOwO Using the latest EFI (2.2.0, pre-released), I can now complete the Ventura installation normally. The keyboard problem has also been solved. THANKS!

you are welcome
