### ISSUE TITLE
关于主题

### ISSUE THREAD

**Issue by 160725** [FluffyCuteOwO/Redmibook14-EE-hackintosh#7]
能不能添加一些好看的主题

**Comment by FluffyCuteOwO** [comment]
你好！. 你想看什么主题？

**Comment by michitta** [comment]
> 能不能添加一些好看的主题

你好！. 你想看什么主题？

**Comment by 160725** [comment]
谢谢大哥，我以为你会很长时间才会回我
图标：http://www.imacosx.cn/6304.html
win图标：https://wallhaven.cc/w/6o6exq
mac图标：https://wallhaven.cc/w/pkmpjj
背景图（里面截一张）：https://www.bilibili.com/video/BV18f4y1o7fd/

**Comment by michitta** [comment]
我很抱歉长时间等待答案，但不幸的是我无法创建这个主题。
