### ISSUE TITLE
Shut down xhc1

### ISSUE THREAD

**Issue by akwangl** [FluffyCuteOwO/Redmibook14-EE-hackintosh#9]
Hello, I am an AMD machine, and only when xhc1 is turned off, can it be installed.  I wonder if intel machines have ever encountered such a situation

**Comment by michitta** [comment]
> Hello, I am an AMD machine, and only when xhc1 is turned off, can it be installed. I wonder if intel machines have ever encountered such a situation

Hi. Sorry for the late reply. No, I have not encountered this problem.
